// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7fwWdqdTvwvRO2AGWkq5HUnzQ7MklxU',
    appId: '1:958027158357:web:f4bf9ab2d6decf447e95dc',
    messagingSenderId: '958027158357',
    projectId: 'behuman-e19ff',
    authDomain: 'behuman-e19ff.firebaseapp.com',
    storageBucket: 'behuman-e19ff.firebasestorage.app',
    measurementId: 'G-S2QM0XFHNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIove732oMk1NU9IZ0IScnXQYSzFGwdSo',
    appId: '1:958027158357:android:1517287a92d5207a7e95dc',
    messagingSenderId: '958027158357',
    projectId: 'behuman-e19ff',
    storageBucket: 'behuman-e19ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYE4QGqYVM5PLev4aQ7Rb3rUUcvfGo9S8',
    appId: '1:958027158357:ios:4dbc815e4eea15017e95dc',
    messagingSenderId: '958027158357',
    projectId: 'behuman-e19ff',
    storageBucket: 'behuman-e19ff.firebasestorage.app',
    iosBundleId: 'com.example.beHuman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYE4QGqYVM5PLev4aQ7Rb3rUUcvfGo9S8',
    appId: '1:958027158357:ios:4dbc815e4eea15017e95dc',
    messagingSenderId: '958027158357',
    projectId: 'behuman-e19ff',
    storageBucket: 'behuman-e19ff.firebasestorage.app',
    iosBundleId: 'com.example.beHuman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ7fwWdqdTvwvRO2AGWkq5HUnzQ7MklxU',
    appId: '1:958027158357:web:31757a45d3ad88707e95dc',
    messagingSenderId: '958027158357',
    projectId: 'behuman-e19ff',
    authDomain: 'behuman-e19ff.firebaseapp.com',
    storageBucket: 'behuman-e19ff.firebasestorage.app',
    measurementId: 'G-2L0E40RRJ1',
  );
}
